### ISSUE TITLE
'Serial3' was not declared in this scope

### ISSUE THREAD

**Issue by NepNutella** [mandulaj/PZEM-004T-v30#10]
Hi, I copied and pasted the code, but the error console is " 'Serial3' was not declared in this scope "..
i using:
Arduino uno, pzem-004T-v30

Thank you!

![image](https://user-images.githubusercontent.com/50035091/62555144-b42ad800-b872-11e9-8a29-f9df64dad01c.png)

**Comment by sergiocntr** [comment]
Serial3 is not available on Arduino Uno,you can use Serial instead. You can follow two routes,the first ,use hardware serial,second use software serial.  I prefer to leave hardware serial for debugging and software serial for pzem interfacing. Each two are easy to implement.

**Comment by NepNutella** [comment]
Oh thanks for the reply. 
Do you have some links to explain this to me?
Thanx so much!

**Comment by sergiocntr** [comment]
You are welcome! That so easy....don't be scared ! Personal thoughts and sorry to say that there are tons of tutorial ,instruction , diy about that and this is not the right place where to ask this question. I know that first steps are hard but you have to do by yourself,I hope you understand. Look on youtube, instructables...You'll find what you are looking for and much more else!!!

**Comment by NepNutella** [comment]
I don't want a link with a code to copy and paste, I wanted a string to search on google!

**Comment by sergiocntr** [comment]
"Software serial arduino uno" maybe? Have you tried? Is this so hard?

**Comment by NepNutella** [comment]
I tried to search but it didn't specifically deal with the topic ... I'm sorry I'll try better

**Comment by mandulaj** [comment]
I see you guys figured it out. Closing this
