### ISSUE TITLE
Reduce RAM usage by storing crcTable in PROGMEM

### ISSUE THREAD

**Issue by growboxguy** [mandulaj/PZEM-004T-v30#11]
Hi, thanks for the module!

You could reduce the RAM usage of the module by declaring crcTable as:
static **PROGMEM** const uint16_t crcTable[]

In this case reading from the crcTable should be updated  to:
crc ^= (uint16_t)pgm_read_word(&crcTable[nTemp]);

**Comment by mandulaj** [comment]
Excellent point! Is this also compatible with ESPs and STM32 (Bluepil)? If yes, I will add it immediately.

**Comment by mandulaj** [comment]
Thanks for the suggestion @growboxguy
