### ISSUE TITLE
instantaneous value

### ISSUE THREAD

**Issue by DuCLeK65t** [mandulaj/PZEM-004T-v30#110]
Can i measure instantaneous voltage and current with phase (not RMS) by PZEM-004T? If then can anyone show me how? Thanks

**Comment by mandulaj** [comment]
No, unfortunately, the PZEM firmware only provides averaged RMS values acquired within the last second or so. For some illogical reason, it also doesn't expose the phase information, only the Power factor which is useless in computing the direction of energy flow.
