### ISSUE TITLE
Set Address not working

### ISSUE THREAD

**Issue by lyinsushi** [mandulaj/PZEM-004T-v30#125]
I'm using ATMega 2560 and arduino ide to change the address of 1 PZEM with the example code. it already connected to AC voltage but it failed to set the new address. To confirm that the ac is not the problem, I try the software serial read example and it read the voltage and other things perfectly.
it output fails is "error setting address"

**Comment by mandulaj** [comment]
Which address are you setting to? Also are you using the standard address setting sketch?

**Comment by lyinsushi** [comment]
apparently it wouldnt work until I erase the hardserial and esp serial code. it works fine now, thanks. I set it from 0x01 to 0x03
