### ISSUE TITLE
How about a new release?

### ISSUE THREAD

**Issue by audaciousengineer** [mandulaj/PZEM-004T-v30#128]
Hi Mandulaj,

first and foremost thank you for creating this nice library!

I was using the release v1.1.2 with PlatformIO when I encountered an issue where my PZEMs would not respond after 49 days 17 hours (pretty precisely). I knew it had to be the millis() function somewhere, but it took me a while to figure out which part of the code did not do well with the overflow. 
Anyways, I found the issue and I was going to submit a pull request so others would not waste their time with it. When I was trying to adapt the code for the pull request I found out that you already fixed it in the master branch. 

Therefore, would you consider to release a new version?

**Comment by mandulaj** [comment]
@audaciousengineer Good point. Done
