### ISSUE TITLE
[Arduino Uno] PZEMSoftwareSerial example

### ISSUE THREAD

**Issue by kozfelipe** [mandulaj/PZEM-004T-v30#15]
Hey guys

Im running PZEMSoftwareSerial example in my arduino uno using 115200 serial baud rate.

Heres my serial output every 2s:
```
Error reading voltage
Error reading current
Error reading power
Error reading energy
Error reading frequency
Error reading power factor

Error reading voltage
Error reading current
Error reading power
Error reading energy
Error reading frequency
Error reading power factor
```

I got my D11 and D12 setup according to example although I got only RX blinking at arduino side and TX blinking at PZEM side.

How can I diagnose this?

**Comment by kozfelipe** [comment]
nevermind Ive inverted my tx/rx

**Comment by mandulaj** [comment]
Yeah happens to the best of us :smile: Maybe this should be better clarified in the examples
