### ISSUE TITLE
Software Serial WemosD1Mini

### ISSUE THREAD

**Issue by SK-sep** [mandulaj/PZEM-004T-v30#22]
I use WeMos D1 Mini and use 2 Pzem which I connect to pin D5-D8 and some other sensors on pin D0-D3
when starting boot must disconnect the pzem from the pin, otherwise the system will not work

**Comment by sergiocntr** [comment]
Hi this is not a issue because wemos as others esp8266 devices fail to boot if  D8 is left high at boot . https://randomnerdtutorials.com/esp8266-pinout-reference-gpios/

**Comment by SK-sep** [comment]
how about D3 or D4 ?

**Comment by sergiocntr** [comment]
Try but boot fail if pulled low....maybe is not your case...you can check in the link above 😉

**Comment by SK-sep** [comment]
thanks for your answer
