### ISSUE TITLE
Arduino 32U4 problem

### ISSUE THREAD

**Issue by DSPQPSK** [mandulaj/PZEM-004T-v30#25]
Hello,
sorry for disturbing you.
Is it possible that there is a problem when using 32U4 processors?

I compile the Soft Serial example with the target Arduino Nano, everything is perfect.
If I now switch to 32U4 based Arduino boards like Leonardo or Micro, then I get the following error:

-----------------------------------------------------------
C:\Program Files\Arduino\hardware\arduino\avr\cores\arduino/USBAPI.h:154:16: note: previous declaration as 'Serial_ Serial'

extern Serial_ Serial;

^~~~~~

exit status 1
-----------------------------------------------------

A similar behavior could be observed if I use the HW Serial example.

Thanks for your support.

**Comment by mandulaj** [comment]
The `extern HardwareSerial Serial` was removed in the new version, so should be fixed now.
