### ISSUE TITLE
Remove EspSoftwareSerial dependecy

### ISSUE THREAD

**Issue by tomy983** [mandulaj/PZEM-004T-v30#57]
**Describe the bug**
In VScode-PlatformIO this declaration causes the compiler to select the latest, but wrong softserial lib version.
remove from library.json and trowing compile error.:
"dependencies": [
        {
            "name": "EspSoftwareSerial",
            "version": ">=3.2.0",
            "platforms": "espressif8266"
        }
    ]
It then will use the one included in the core.
more explanation here:
https://community.platformio.org/t/softwareserial-not-compiling/19578

**Comment by mandulaj** [comment]
PR was merged so closing issue
