### ISSUE TITLE
Deleting a PZEM004Tv30 on SoftwareSerial leaks memory

### ISSUE THREAD

**Issue by FXeio** [mandulaj/PZEM-004T-v30#61]
**Describe the bug**
When the destructor is called on a PZEM004Tv30 using SoftwareSerial, the library deletes the _serial, but _serial is declared as Stream*, which doesn't actually call the proper SoftwareSerial's destructor

**To Reproduce**
1. Create a new PZEM004Tv30 using SoftwareSerial
2. Delete it
3. SoftwareSerial is not closed and memory is leaked (on Espressif platforms you can check this with ESP.freeHeap())

**Comment by mandulaj** [comment]
Great catch! I will merge this right away!
