### ISSUE TITLE
Problem Compiling ''PZEMHardSerial'' 

### ISSUE THREAD

**Issue by OctubreRojo** [mandulaj/PZEM-004T-v30#73]
I have a problem compiling PZEMHardSerial on Arduino IDE 1.8.15 for ESP32. It shows me this message: '' exit status 1
no matching function for call to 'PZEM004Tv30::PZEM004Tv30(HardwareSerial&, int, int)'  ''
Does anybody knows how can I solve this? Or which arduino IDE version should I use?

![image](https://user-images.githubusercontent.com/35820717/127356947-baefc87c-674c-4ccc-8ff2-461ce33e9c1f.png)

**Comment by mandulaj** [comment]
Have you by chance installed the old version of the library earlier? It looks like there is some kind of a conflict and Arduino can't find the current version source files. I've just tried it on my Arduino 1.8.15 and the PZEMHardSerial example compiled OK. Also could you post a bit more of your source code.

**Comment by OctubreRojo** [comment]
I think you're right. Probably what I did is that I installed olehs' library and then yours. (Not sure if I had the previous version of your library). I've just installed Arduino and your library in another pc and compiled with no problem. 
Thank you very much.

**Comment by mandulaj** [comment]
No problem. I've just recently added the library to the Arduino Library Manager and I am expecting similar issues to come up. I think many people had it manually installed before and I have no idea how the Arduino IDE handles this. From my personal experience, it usually creates a new folder and then all sorts of duplicate header issues can come up. I will close your issue for now if that is ok.
