### ISSUE TITLE
Connect 3 PZEM to 3 different serial ports

### ISSUE THREAD

**Issue by Pippozz** [mandulaj/PZEM-004T-v30#84]
Hi everyone!
I need to connect 3 different PZEM to 3 different serial ports to an ESP32 (or if necessary an esp8266)
How can I do it with this library?

I can't set addresses to pzem and call it a day since I need to swap them quite frequently and I don't want my mesures messed up...

Thanks in advance!

**Comment by sergiocntr** [comment]
Hi
Take a look at closed issue #64

**Comment by vortigont** [comment]
@Pippozz 
you can also check the alternative [pzem-edl](https://github.com/vortigont/pzem-edl) lib oriented to multi device connections
