### ISSUE TITLE
Reading apparent energy 

### ISSUE THREAD

**Issue by mohannad999** [mandulaj/PZEM-004T-v30#91]
How I can read apparent energy from pzem module?

**Comment by mandulaj** [comment]
Hi @mohannad999, The module, unfortunately, doesn't integrate Apparent energy. It hardly lets you get at any of the complex power. You could use the power factor and the Active power (together with some trigonometry) to compute the apparent power and then integrate it over time to get Apparent energy. But it will not be very accurate, especially if you integrate it over large time steps. Refer to https://en.wikipedia.org/wiki/AC_power Best of luck
